### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by nsubiron** [carla-simulator/carla#142]
Our documentation needs a boost!

- [x] [Community profile](https://github.com/carla-simulator/carla/community)
- [x] Hands-on tutorial
- [x] How to run headless
- [x] How to chose GPU when running headless #116
- [x] How to create your own scenarios with our tools #110
- [x] Running CARLA server in-editor #143
- [ ] Software design #145 
- [ ] How many cars and pedestrians can you add? #171
- [ ] More FAQ/Troubleshooting (get from [questions list](https://github.com/carla-simulator/carla/issues?q=is%3Aissue+label%3Aquestion+sort%3Acomments-desc) and [add to documentation](https://github.com/carla-simulator/carla/labels/add%20to%20documentation))
- [x] Better road-map
- [ ] Suggestions?

All contributions are appreciated ;) 

Submit your commits/pull-requests to the `documentation` branch.

**Comment by felipecode** [comment]
Adding a clear and aesthetically pleasing project roadmap, both in short and in long term goals.

**Comment by germanros1987** [comment]
New documentation can be found here: https://carla.readthedocs.io/en/latest

Thanks to @sergi-e for his amazing work!
