### ISSUE TITLE
Redefining client side agents.

### ISSUE THREAD

**Issue by felipecode** [carla-simulator/carla#428]
## Introduction
Right now there are two ways to control the player vehicle. Manually, by sending commands to the server, or through the autopilot option. With the autopilot option, the player vehicle is controlled by an agent programmed to follow the lane from the map and take random decision or curves. 

However, this agent is programmed inside the unreal module and lacks flexibility and integration
provided by the python API. Our objective is to have a multi-agent api where all the agents could be scripted in python in the client side. 
Currently, we only support one agent to be controlled by the client each time and our client agent is very limited. This topic describes the redefinition we want to make for the client side agent architecture and code, as well as adding more agents. 

## The Agent Module Overview.
![agentarch](https://user-images.githubusercontent.com/4934673/40191728-9a0a4c46-5a02-11e8-84d9-bcc332feb1bc.png)

There is a super class "agent" that can be redefined by different agents types. This interface is necessary so each agent can be benchmarked , or in the future, be part of a situation script. Check how the benchmark class works. http://carla.readthedocs.io/en/latest/benchmark_structure/

For now we have the Human agent implemented as the "manual control " example outside this structure. We have a the trivial forward agent. We have the Command follower , that is very similar to a lane follower, implemented ( not working ) on the client side agent branch.

## What we want to do

General

- [x] Implement a more general planner that can produce waypoints, commands etc. WontFix for now, see #468 
- [x] Reorganize the architecture structure.

Human Agent
- [ ]  Implement a joystick module that respects this architecture #88
- [ ]  Implement a visualization module better than the one we have on the manual control example  #421 

Command/ Lane followers from https://github.com/carla-simulator/carla/tree/client_side_agent
- [x] Update it to version 0.8.2
- [ ] Eliminate the bugs
- [ ] Document the strategy
- [ ] Reformat the code style
- [x] Put inside the new architecture

Keep in mind that this architecture is able to change, suggestions are welcome. Cheers guys !

EDIT: 

Progress report
28/05/2018
Created the branch. https://github.com/carla-simulator/carla/tree/CS1_client_side_agents
Started the organization of the new architecture
29/05/2018
Started porting the old client side agent to the new architecture. It will be used to make the lane follower and the command follower.

 The waypointer class needs to improved. Unit tests for that class needs to be added.

24/06/2018
Added a working version of the client side agent.
