### ISSUE TITLE
Load additional assets in runtime

### ISSUE THREAD

**Issue by juaxix** [carla-simulator/carla#438]
## Introduction
Load additional assets in runtime (task) is a part of the **Map and CARLA Binary Detachment** process.

Right now there is no way to load any external asset in runtime,but it is possible to add assets for the release, by versioning or [patching](https://docs.unrealengine.com/en-us/Engine/Deployment/Patching) the assets in a pak file,that is loaded at the launching time of the engine load process. But we should be able to load assets in runtime using code, triggered by executing a command from a client or from direct code in the game.

## What we want to do
CARLA-client can  load new scenarios and assets that lives outside the server binary

## Streaming: Loading assets as stream (local or remote)
- Using [AssetManager](https://docs.unrealengine.com/en-us/Engine/Basics/AssetsAndPackages/AssetManagement)
- Using Streaming and PlatformFile libraries from Unreal Engine
- Loading PAKs in runtime using [this AsyncPackageStreamer plugin](https://github.com/moritz-wundke/AsyncPackageStreamer) ( MIT license )
- Load additional files using this [zip utility plugin](https://github.com/getnamo/ZipUtility-ue4) (MIT license)
- Automatically generate and build DLC plugins adapting [this tool](https://github.com/calben/CharacterPluginGenerator)

#### Pre-Required:
- [x] Carla Spectator ( #445 ) : a default Spectator Pawn class to be controlled by the player controller
- [x] Map change by map name ( #65 ): a way to change the current map to another one set in the level settings 
- [x] Design a pipeline for creating DLCs (  #460 ): howto to create a plugin with additional contents
- [x] Design a method for creating patches ( #475 )
- [ ] Transition map ( #483 ):  a level used to start and change to another persistent level on demand

**Comment by felipecode** [comment]
With respect to map change, check my PR #472
